from openai import OpenAI
import config

_SYSTEM_PROMPT = """You are a professional technical interviewer conducting a phone screening call.

STRICT RULES — follow these exactly:
- Ask ONE question at a time. Nothing else.
- Do NOT give feedback on answers. No "great answer", "good to hear", "interesting", "that makes sense".
- Do NOT say "let me think", "hmm", "I see", or any filler.
- Do NOT summarise what the candidate said back to them.
- Do NOT compliment or critique any answer.
- After the candidate answers, move DIRECTLY to the next question.
- Keep every response under 25 words.
- After 5 questions say INTERVIEW_COMPLETE then a brief goodbye.

GOOD example response:
"How have you handled database optimisation in your projects?"

BAD example response:
"Great answer! It sounds like you have solid Java experience. Let me think about that. My next question is about databases."

JOB DESCRIPTION:
{job_description}

CANDIDATE RESUME:
{resume_text}

Questions asked so far: {question_count}
"""


class Interviewer:
    def __init__(self, resume_text: str, job_description: str):
        self.client = OpenAI(api_key=config.OPENAI_API_KEY)
        self.model = "gpt-4o-mini"
        self.resume_text = resume_text
        self.job_description = job_description
        self.conversation_history = []
        self.question_count = 0
        self.is_complete = False

    def get_opening_message(self) -> str:
        """
        Returns the fixed opening line the AI says when the call connects.
        Hardcoded for speed and consistency — not generated by GPT.
        """
        return (
            "Hello, I am calling from the hiring team for a short "
            "technical screening. I will ask you five questions. "
            "Please take your time with each answer. "
            "First question — can you walk me through your most "
            "recent role and what you built there?"
        )

    def is_sufficient_answer(self, text: str) -> bool:
        words = text.split()
        if len(words) < 5:
            return False
        filler_only = {"yes", "no", "okay", "ok", "sure", "yeah",
                       "um", "uh", "hmm", "right", "fine"}
        non_filler = [w for w in words if w.lower() not in filler_only]
        return len(non_filler) >= 4

    def generate_response(self, candidate_utterance: str) -> str:
        """
        Given what the candidate just said, decide what the interviewer says next.

        Returns the text response to speak.
        Sets self.is_complete = True when GPT signals INTERVIEW_COMPLETE.
        """
        if not self.is_sufficient_answer(candidate_utterance):
            print(f"[Interviewer] Short answer, prompting for more: '{candidate_utterance}'")
            return "Could you tell me a bit more about that?"

        self.conversation_history.append({
            "role": "user",
            "content": candidate_utterance,
        })
        self.question_count += 1

        system_content = _SYSTEM_PROMPT.format(
            job_description=self.job_description,
            resume_text=self.resume_text[:2000],
            question_count=self.question_count,
        )
        messages = [{"role": "system", "content": system_content}] + self.conversation_history

        response = self.client.chat.completions.create(
            model=self.model,
            messages=messages,
            max_tokens=150,
            temperature=0.7,
        )

        reply = response.choices[0].message.content.strip()

        if "INTERVIEW_COMPLETE" in reply:
            self.is_complete = True
            reply = reply.replace("INTERVIEW_COMPLETE", "").strip()
            if not reply:
                reply = (
                    "That is all the questions I have for you today. "
                    "Thank you so much for your time. "
                    "The hiring team will be in touch with next steps. "
                    "Have a great day!"
                )

        self.conversation_history.append({
            "role": "assistant",
            "content": reply,
        })

        print(f"[Interviewer] Q{self.question_count}: {reply[:80]}...")
        return reply

    def get_full_transcript(self) -> str:
        """
        Returns the full conversation as a readable transcript
        for the reporter to generate the final score and summary.
        """
        lines = []
        for msg in self.conversation_history:
            role = "Interviewer" if msg["role"] == "assistant" else "Candidate"
            lines.append(f"{role}: {msg['content']}")
        return "\n\n".join(lines)
